<?php

namespace Database\Seeders;

use App\Models\MasjidSurau;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MasjidSurauSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data first
        MasjidSurau::truncate();
        
        $masjidSuraus = [
            [
                'nama' => 'Masjid Tengku Ampuan Jemaah',
                'singkatan_nama' => 'MTAJ',
                'jenis' => 'Masjid',
                'alamat_baris_1' => 'Jalan Sultan Abdul Aziz Shah',
                'alamat_baris_2' => 'Bukit Jelutong',
                'alamat_baris_3' => null,
                'poskod' => '40150',
                'bandar' => 'Shah Alam',
                'negeri' => 'Selangor',
                'negara' => 'Malaysia',
                'daerah' => 'Petaling',
                'no_telefon' => '03-78461234',
                'email' => 'mtaj@gmail.com',
                'imam_ketua' => 'Ustaz Ahmad bin Abdullah',
                'bilangan_jemaah' => 500,
                'tahun_dibina' => 1995,
                'status' => 'Aktif',
                'catatan' => 'Masjid utama kawasan Bukit Jelutong dengan kapasiti jemaah yang besar.',
            ],
            [
                'nama' => 'Surau At-Taqwa',
                'singkatan_nama' => 'SAT',
                'jenis' => 'Surau',
                'alamat_baris_1' => 'Taman Bukit Jelutong',
                'alamat_baris_2' => 'Seksyen U8',
                'alamat_baris_3' => null,
                'poskod' => '40150',
                'bandar' => 'Shah Alam',
                'negeri' => 'Selangor',
                'negara' => 'Malaysia',
                'daerah' => 'Petaling',
                'no_telefon' => '03-78461235',
                'email' => 'attaqwa@gmail.com',
                'imam_ketua' => 'Encik Mohd Ali bin Hassan',
                'bilangan_jemaah' => 150,
                'tahun_dibina' => 2005,
                'status' => 'Aktif',
                'catatan' => 'Surau komuniti untuk penduduk Taman Bukit Jelutong.',
            ],
            [
                'nama' => 'Masjid Al-Hidayah',
                'singkatan_nama' => 'MAH',
                'jenis' => 'Masjid',
                'alamat_baris_1' => 'Seksyen 3',
                'alamat_baris_2' => 'Jalan Tengku Ampuan Zabedah A9/A',
                'alamat_baris_3' => null,
                'poskod' => '40000',
                'bandar' => 'Shah Alam',
                'negeri' => 'Selangor',
                'negara' => 'Malaysia',
                'daerah' => 'Petaling',
                'no_telefon' => '03-55121234',
                'email' => 'alhidayah@gmail.com',
                'imam_ketua' => 'Ustaz Ibrahim bin Yusuf',
                'bilangan_jemaah' => 800,
                'tahun_dibina' => 1980,
                'status' => 'Aktif',
                'catatan' => 'Masjid bersejarah di Seksyen 3 Shah Alam.',
            ],
            [
                'nama' => 'Surau An-Nur',
                'singkatan_nama' => 'SAN',
                'jenis' => 'Surau',
                'alamat_baris_1' => 'Bandar Baru Klang',
                'alamat_baris_2' => 'Jalan Tiara 2A',
                'alamat_baris_3' => null,
                'poskod' => '41150',
                'bandar' => 'Klang',
                'negeri' => 'Selangor',
                'negara' => 'Malaysia',
                'daerah' => 'Klang',
                'no_telefon' => '03-33451234',
                'email' => 'annur@gmail.com',
                'imam_ketua' => 'Encik Zainal bin Ahmad',
                'bilangan_jemaah' => 200,
                'tahun_dibina' => 2010,
                'status' => 'Aktif',
                'catatan' => 'Surau moden dengan kemudahan lengkap.',
            ],
            [
                'nama' => 'Masjid Jamek Petaling Jaya',
                'singkatan_nama' => 'MJPJ',
                'jenis' => 'Masjid',
                'alamat_baris_1' => 'Seksyen 14',
                'alamat_baris_2' => 'Jalan 14/22',
                'alamat_baris_3' => null,
                'poskod' => '46100',
                'bandar' => 'Petaling Jaya',
                'negeri' => 'Selangor',
                'negara' => 'Malaysia',
                'daerah' => 'Petaling',
                'no_telefon' => '03-79551234',
                'email' => 'mjpj@gmail.com',
                'imam_ketua' => 'Ustaz Rahman bin Omar',
                'bilangan_jemaah' => 600,
                'tahun_dibina' => 1975,
                'status' => 'Aktif',
                'catatan' => 'Masjid jamek utama Petaling Jaya dengan sejarah panjang.',
            ],
            [
                'nama' => 'Surau Ar-Rahman',
                'singkatan_nama' => 'SAR',
                'jenis' => 'Surau',
                'alamat_baris_1' => 'Taman Subang Jaya',
                'alamat_baris_2' => 'Jalan SS15/4A',
                'alamat_baris_3' => null,
                'poskod' => '47500',
                'bandar' => 'Subang Jaya',
                'negeri' => 'Selangor',
                'negara' => 'Malaysia',
                'daerah' => 'Petaling',
                'no_telefon' => '03-56331234',
                'email' => 'arrahman@gmail.com',
                'imam_ketua' => 'Encik Rashid bin Mahmud',
                'bilangan_jemaah' => 120,
                'tahun_dibina' => 2015,
                'status' => 'Aktif',
                'catatan' => 'Surau baharu dengan reka bentuk moden.',
            ],
            [
                'nama' => 'Masjid Negara',
                'singkatan_nama' => 'MN',
                'jenis' => 'Masjid',
                'alamat_baris_1' => 'Jalan Perdana',
                'alamat_baris_2' => 'Tasik Perdana',
                'alamat_baris_3' => null,
                'poskod' => '50480',
                'bandar' => 'Kuala Lumpur',
                'negeri' => 'Wilayah Persekutuan Kuala Lumpur',
                'negara' => 'Malaysia',
                'daerah' => 'Kuala Lumpur',
                'no_telefon' => '03-26935435',
                'email' => 'masjidn@gov.my',
                'imam_ketua' => 'Dato\' Ustaz Hasan bin Ali',
                'bilangan_jemaah' => 15000,
                'tahun_dibina' => 1965,
                'status' => 'Aktif',
                'catatan' => 'Masjid kebangsaan Malaysia dengan seni bina yang unik dan bersejarah.',
            ],
            [
                'nama' => 'Surau Al-Ikhlas',
                'singkatan_nama' => 'SAI',
                'jenis' => 'Surau',
                'alamat_baris_1' => 'Kampung Baru',
                'alamat_baris_2' => 'Jalan Raja Muda Abdul Aziz',
                'alamat_baris_3' => null,
                'poskod' => '50300',
                'bandar' => 'Kuala Lumpur',
                'negeri' => 'Wilayah Persekutuan Kuala Lumpur',
                'negara' => 'Malaysia',
                'daerah' => 'Kuala Lumpur',
                'no_telefon' => '03-26921234',
                'email' => 'alikhlas@gmail.com',
                'imam_ketua' => 'Haji Mahmud bin Ibrahim',
                'bilangan_jemaah' => 80,
                'tahun_dibina' => 1960,
                'status' => 'Tidak Aktif',
                'catatan' => 'Surau lama yang memerlukan pembaikan dan pengubahsuaian.',
            ],
            [
                'nama' => 'Masjid Sultan Salahuddin Abdul Aziz',
                'singkatan_nama' => 'MSSAA',
                'jenis' => 'Masjid',
                'alamat_baris_1' => 'Persiaran Masjid',
                'alamat_baris_2' => 'Seksyen 14',
                'alamat_baris_3' => null,
                'poskod' => '40000',
                'bandar' => 'Shah Alam',
                'negeri' => 'Selangor',
                'negara' => 'Malaysia',
                'daerah' => 'Petaling',
                'no_telefon' => '03-55444000',
                'email' => 'masjidnegeri@selangor.gov.my',
                'imam_ketua' => 'Dato\' Ustaz Mohd Yusof bin Ahmad',
                'bilangan_jemaah' => 24000,
                'tahun_dibina' => 1988,
                'status' => 'Aktif',
                'catatan' => 'Masjid negeri Selangor, dikenali sebagai Masjid Biru dengan kubah biru yang terkenal.',
            ],
            [
                'nama' => 'Surau Al-Falah',
                'singkatan_nama' => 'SAF',
                'jenis' => 'Surau',
                'alamat_baris_1' => 'Taman Melawati',
                'alamat_baris_2' => 'Jalan Melawati 1',
                'alamat_baris_3' => null,
                'poskod' => '53100',
                'bandar' => 'Kuala Lumpur',
                'negeri' => 'Wilayah Persekutuan Kuala Lumpur',
                'negara' => 'Malaysia',
                'daerah' => 'Gombak',
                'no_telefon' => '03-41061234',
                'email' => 'alfalah@gmail.com',
                'imam_ketua' => 'Ustaz Farid bin Hashim',
                'bilangan_jemaah' => 180,
                'tahun_dibina' => 2008,
                'status' => 'Aktif',
                'catatan' => 'Surau komuniti yang aktif dengan pelbagai program keagamaan.',
            ],
        ];

        foreach ($masjidSuraus as $data) {
            MasjidSurau::create($data);
        }
    }
}
